### ISSUE TITLE
Cannot set unknown key "baseDir" on Record

### ISSUE THREAD

**Issue by wwwebman** [shanecav/webpack-browsersync-proxy#1]
after `yarn start` an error occur, please check
ubuntu 17.10, node 8

**Comment by shanecav** [comment]
Hi, sorry it's not working. I wrote this example 2 years ago, and haven't really touched it since. A lot has changed since then with webpack, and I think accomplishing something like this is easier now than it was when I originally put this together. I'd recommend checking out the latest version of webpack - this repo is pretty outdated now.
